#! /usr/bin/env perl
#
#        Name: DisplayMeeting
# Description: Displays talks for a meeting or just a session of a meeting
#
#    Revision: $Revision$
#    Modified: $Author$ on $Date$
#
#      Author: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use Benchmark;
use CGI;
use CGI::Untaint;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "Messages.pm";

require "HTMLUtilities.pm";
require "UntaintInput.pm";
require "ResponseElements.pm";
require "Sorts.pm";
require "Scripts.pm";
require "Security.pm";
require "MeetingSecurityUtilities.pm";

require "MeetingHTML.pm";
require "DocumentHTML.pm";
require "MeetingSQL.pm";
require "RevisionSQL.pm";
require "TalkSQL.pm";

require "TalkHintUtilities.pm";
require "DocumentUtilities.pm";
require "EventUtilities.pm";
require "Utilities.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
my $Untaint = CGI::Untaint -> new($query -> Vars);

my $SessionID = $Untaint -> extract(-as_integer => "sessionid") || 0;
my $SessionSeparatorID = $Untaint -> extract(-as_integer => "sessionseparatorid") || 0;
my $EventID = $Untaint -> extract(-as_integer => "conferenceid") || 0;

@ErrorStack = ();
@WarnStack  = ();

$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}

my $PageTitle = "Unknown Event";
if (!$dbh) {
  $PageTitle = "Database Error";
} elsif ($SessionID ) {
  FetchSessionByID($SessionID);
  $PageTitle = $Sessions{$SessionID}{Title};
} elsif ($SessionSeparatorID) {
  FetchSessionSeparatorByID($SessionSeparatorID);
  $PageTitle = $SessionSeparators{$SessionSeparatorID}{Title};
} else {
  FetchConferenceByConferenceID($EventID);
  $PageTitle = $Conferences{$EventID}{Title};
}

my @Scripts = ("PopUps");
push @Scripts,"jquery/jquery-3.5.1.slim.min","jquery/jquery.tablesorter.min","jquery/jquery.tablesorter.widgets";
@JQueryElements = ("tablesorter");
push @Scripts,"JQueryReady";

print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader($PageTitle, "", -scripts => \@Scripts, -jqueryelements => \@JQueryElements);
EndPage(@ErrorStack);

my $DisplayMode = ""; # 4 choices: Event, SingleSession(Event), Session, Separator

if ($EventID) {
  $DisplayMode = "Event";
  my @MeetingOrderIDs = FetchMeetingOrdersByConferenceID($EventID);
  @MeetingOrderIDs = sort MeetingOrderIDByOrder @MeetingOrderIDs;
  if (scalar(@MeetingOrderIDs) == 1) { # If just one session, switch to SingleSession mode
    $DisplayMode    = "SingleSession";
    $MeetingOrderID = pop @MeetingOrderIDs;
    $SessionID      = $MeetingOrders{$MeetingOrderID}{SessionID};
  }
} elsif ($SessionID) {
  $DisplayMode = "Session";
  FetchSessionByID($SessionID);
  $EventID = $Sessions{$SessionID}{ConferenceID};
  my @MeetingOrderIDs = FetchMeetingOrdersByConferenceID($EventID);
  @MeetingOrderIDs = sort MeetingOrderIDByOrder @MeetingOrderIDs;
  if ($#MeetingOrderIDs == 0) { # If just one session, switch to SingleSession mode
    $DisplayMode = "SingleSession";
  }
} elsif ($SessionSeparatorID) {
  $DisplayMode = "Separator";
  FetchSessionSeparatorByID($SessionSeparatorID);
  $EventID = $SessionSeparators{$SessionSeparatorID}{ConferenceID};
}

FetchEventByEventID($EventID);
unless ($Conferences{$EventID}{TimeStamp}) {
  push @ErrorStack,"No such event exists.";
}
unless (CanAccessMeeting($EventID)) {
  push @ErrorStack,$Msg_MeetNoAccess;
}
EndPage(@ErrorStack);

# Rehint talks

if ($DisplayMode eq "Session" || $DisplayMode eq "SingleSession") {
  ReHintTalksBySessionID($SessionID);
  FetchSessionByID($SessionID);
} elsif ($DisplayMode eq $Event) {
  my @SessionIDs = FetchSessionsByConferenceID($EventID);
  foreach my $SessionID (@SessionIDs) {
    ReHintTalksBySessionID($SessionID);
  }
}
ClearSessionTalks();

### Get list of docs that are not on agenda

my @AgendaDocIDs   = EventAgendaDocIDs({-eventid => $EventID});
my @AllRevisionIDs = FetchRevisionsByEventID($EventID);
my @AllDocIDs      = RevisionToDocumentIDs({-revisionids => \@AllRevisionIDs});
my @UnusedDocIDs   = RemoveArray(\@AllDocIDs,@AgendaDocIDs);

print "<div id=\"MeetingBodyWrapper\" class=\"w3-container\">\n";

### Header Section
print "<div id=\"MeetingHeadWrap\" style=\"display:flex;gap:16px;align-items:flex-start;\">\n";

### Left Column: Form Module
print "<div id=\"MeetingHeadLeftCol\" class=\"\" style=\"flex:0 0 auto;vertical-align:top;width:fit-content;\">\n";
PrintEventLeftSidebar({ -sessionid   => $SessionID,          -eventid => $EventID,
                        -separatorid => $SessionSeparatorID, -displaymode => $DisplayMode,
                        -nextradocs  => scalar(@UnusedDocIDs),
                     });
print "</div><!-- Closing div id MeetingHeadLeftCol -->\n";

### Event Information
print "<div id=\"MeetingHeadEventInformation\" class=\"\" style=\"flex:1 1 auto;min-width:0;vertical-align:top;\">\n";
print EventHeader( {-sessionid => $SessionID, -eventid => $EventID, -separatorid => $SessionSeparatorID, -displaymode => $DisplayMode} );
print "</div><!-- Closing div id MeetingHeadEventInformation -->\n";

print "</div><!-- Closing div id MeetingHeadWrap -->\n";

### Session Table Section (clean break/new line)
print "<div id=\"EventScheduleMain\" class=\"w3-margin-top w3-margin-bottom\">\n";

### Session Schedule

print "<div id=\"SessionSchedule\" class=\"w3-center w3-border w3-border-black\">\n";

if ($DisplayMode eq "Session" || $DisplayMode eq "SingleSession") { # Display a single session
  PrintSession(-sessionid => $SessionID, -skipheader => $TRUE);
} elsif ($DisplayMode eq "Event") { # Display meeting info or meeting with all talks
  my @MeetingOrderIDs = FetchMeetingOrdersByConferenceID($EventID);
  @MeetingOrderIDs = sort MeetingOrderIDByOrder @MeetingOrderIDs;

# FIXME: Awl -> All to restore previous behavior, remove Conferences test from ~20 lines below
# Check separator before deciding
  if ($Conferences{$EventID}{ShowAwlTalks}) { # Display all talks, sessions
    foreach $MeetingOrderID (@MeetingOrderIDs) { # Loop over sessions/breaks
      my $SessionID          = $MeetingOrders{$MeetingOrderID}{SessionID};
      my $SessionSeparatorID = $MeetingOrders{$MeetingOrderID}{SessionSeparatorID};
      if ($SessionID) {
        FetchSessionByID($SessionID);
        PrintSession(-sessionid => $SessionID); # Display a single session
      } elsif ($SessionSeparatorID) {
        FetchSessionSeparatorByID($SessionSeparatorID);
        PrintSessionSeparator($SessionSeparatorID); # Display session separator
      }
    }
  } else { # Display links to sessions and info on separators
    print '<table class="w3-table w3-bordered w3-center w3-white" id="SessionList">';
    print "<thead class=\"w3-light-gray\"><tr><th>Date &amp; Time</th><th>Session</th><th>Session Information</th>\n";
    print "<th>Location</th><th>Topic(s)</th><th>Moderator(s)</th></tr></thead><tbody>\n";

    foreach $MeetingOrderID (@MeetingOrderIDs) {
      my $SessionID          = $MeetingOrders{$MeetingOrderID}{SessionID};
      my $SessionSeparatorID = $MeetingOrders{$MeetingOrderID}{SessionSeparatorID};
      if ($SessionID) {              # Session info and link to session
        if ($Sessions{$SessionID}{ShowAllTalks} || $Conferences{$EventID}{ShowAllTalks}) {
          FetchSessionByID($SessionID);
          print SessionInfo($SessionID); # Does own <tr>
          print "<tr>".'<td id="EmbedSession" class="w3-light-gray" colspan="6" style="margin:0!important;padding:3px!important;">';
          PrintSession(-sessionid => $SessionID, -onlytalks => $TRUE); # Display a single session
          print '</td></tr>';
        } else {
          print SessionInfo($SessionID); # Does own <tr>
        }
      } elsif ($SessionSeparatorID) {
        print "<tr>\n";
        PrintSessionSeparatorInfo($SessionSeparatorID); # SessionSeparator info
        print "</tr>\n";
      }
    }
    print "</tbody></table>\n";
  }

# Finish off meeting display

  PrintMeetingEpilogue($EventID);
}

# Display talks not associated with sessions

if ($DisplayMode eq "Event" || $DisplayMode eq "SingleSession") {
  if (@UnusedDocIDs) {
    print "<h4>Other documents for this event</h4>\n";
    my %FieldList = PrepareFieldList(-default => "Default");
    my $NumberOfDocuments = DocumentTable(-fieldlist => \%FieldList,
         -docids  => \@UnusedDocIDs, -sortby  => "date",
         -reverse => $TRUE);
    print "<hr/>\n";
  }
}

print "</div><!-- Closing div id SessionSchedule -->\n";
print "</div><!-- Closing div id EventScheduleMain -->\n";
print "</div><!-- Closing div id MeetingBodyWrapper -->\n";

$EndTime  = new Benchmark;

DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

exit;
